export interface EnvironmentVariables {
  NX_GOOGLE_CLIENT_ID: string;
  NX_GOOGLE_CLIENT_SECRET: string;

  NX_JWT_ACCESS_TOKEN_SECRET: string;
  NX_JWT_ACCESS_TOKEN_EXPIRATION_TIME: number;

  NX_JWT_REFRESH_TOKEN_SECRET: string;
  NX_JWT_REFRESH_TOKEN_EXPIRATION_TIME: number;
}
